name: wasm build
on: [push, pull_request]
jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /__w/quisp/quisp
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: wasm build
        uses: zigen/omnetpp-wasm@v0.27
      - uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: |
            quisp/out/emcc-release/*.html
            quisp/out/emcc-release/*.js
            quisp/out/emcc-release/*.data
            quisp/out/emcc-release/*.wasm
            quisp/out/emcc-release/*.svg
            quisp/out/emcc-release/*.css
  deploy-wasm:
    needs: build-wasm
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/demo-')) }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'sfc-aqua/quisp-online'
      - uses: actions/download-artifact@v4
        with:
          name: wasm-build
      - name: setup git
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "$DEPLOY_KEY" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config remote.origin.url  "git@github.com:sfc-aqua/quisp-online"
          git config user.name "GitHub Actions Bot"
          git config user.email "sfc-aqua@users.noreply.github.com"
      - name: commit master branch
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          rm -rf master
          mkdir -p master
          mv quisp.js quisp.data quisp.wasm index.html qtlogo.svg qtloader.js main.js style.css master
          git add master
          git commit -m "[master] wasm build: https://github.com/sfc-aqua/quisp/commit/$GITHUB_SHA"
      - name: commit tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          export TAG=$(echo $GITHUB_REF | sed -e 's/refs\/tags\///')
          mkdir -p $TAG
          mv quisp.js quisp.data quisp.wasm index.html qtlogo.svg qtloader.js main.js style.css $TAG
          git add $TAG
          git commit -m "[$TAG] wasm build: https://github.com/sfc-aqua/quisp/commit/$GITHUB_SHA"
      - name: commit demo branch
        if: ${{ startsWith(github.ref, 'refs/heads/demo-') }}
        run: |
          export BRANCH=$(echo $GITHUB_REF | sed -e 's/refs\/heads\/demo-//')
          mkdir -p $BRANCH
          ls -la
          mv quisp.js quisp.data quisp.wasm index.html qtlogo.svg qtloader.js main.js style.css $BRANCH
          git add $BRANCH
          git commit -m "[$BRANCH] wasm build: https://github.com/sfc-aqua/quisp/commit/$GITHUB_SHA"
      - name: push
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          git push origin master -f
